"""
童科绘提示词模板模块
包含所有智能体的优化提示词
"""
from .story_creator_prompt import STORY_SUGGEST_SYSTEM_PROMPT, STORY_SUGGEST_USER_PROMPT_TEMPLATE
from .story_creator_prompt_fun import STORY_CREATOR_FUN_SYSTEM_PROMPT, STORY_CREATOR_FUN_USER_PROMPT_TEMPLATE
from .story_creator_prompt_encyclopedia import STORY_CREATOR_ENC_SYSTEM_PROMPT, STORY_CREATOR_ENC_USER_PROMPT_TEMPLATE
from .science_checker_prompt import SCIENCE_CHECKER_SYSTEM_PROMPT, SCIENCE_CHECKER_USER_PROMPT_TEMPLATE
from .reader_prompt import READER_SYSTEM_PROMPT, READER_USER_PROMPT_TEMPLATE
from .illustrator_prompt import ILLUSTRATOR_SYSTEM_PROMPT, ILLUSTRATOR_USER_PROMPT_TEMPLATE
from .literature_checker_prompt import LITERATURE_CHECKER_SYSTEM_PROMPT, LITERATURE_CHECKER_USER_PROMPT_TEMPLATE
from .publisher_prompt import PUBLISHER_SYSTEM_PROMPT, PUBLISHER_USER_PROMPT_TEMPLATE
from .self_feedback_science_prompt import (
    INITIAL_REVIEW_SYSTEM_PROMPT,
    INITIAL_REVIEW_USER_PROMPT,
    FEEDBACK_GENERATION_SYSTEM_PROMPT,
    FEEDBACK_GENERATION_USER_PROMPT,
    ITERATIVE_OPTIMIZATION_SYSTEM_PROMPT,
    ITERATIVE_OPTIMIZATION_USER_PROMPT,
    CITATION_VERIFICATION_SYSTEM_PROMPT,
    CITATION_VERIFICATION_USER_PROMPT,
    WORKFLOW_SUMMARY_PROMPT,
)

__all__ = [
    "STORY_SUGGEST_SYSTEM_PROMPT",
    "STORY_SUGGEST_USER_PROMPT_TEMPLATE",
    "STORY_CREATOR_FUN_SYSTEM_PROMPT",
    "STORY_CREATOR_FUN_USER_PROMPT_TEMPLATE",
    "STORY_CREATOR_ENC_SYSTEM_PROMPT",
    "STORY_CREATOR_ENC_USER_PROMPT_TEMPLATE",
    "SCIENCE_CHECKER_SYSTEM_PROMPT",
    "SCIENCE_CHECKER_USER_PROMPT_TEMPLATE",
    "READER_SYSTEM_PROMPT",
    "READER_USER_PROMPT_TEMPLATE",
    "ILLUSTRATOR_SYSTEM_PROMPT",
    "ILLUSTRATOR_USER_PROMPT_TEMPLATE",
    "LITERATURE_CHECKER_SYSTEM_PROMPT",
    "LITERATURE_CHECKER_USER_PROMPT_TEMPLATE",
    "PUBLISHER_SYSTEM_PROMPT",
    "PUBLISHER_USER_PROMPT_TEMPLATE",
    # 自反馈科学审核提示词
    "INITIAL_REVIEW_SYSTEM_PROMPT",
    "INITIAL_REVIEW_USER_PROMPT",
    "FEEDBACK_GENERATION_SYSTEM_PROMPT",
    "FEEDBACK_GENERATION_USER_PROMPT",
    "ITERATIVE_OPTIMIZATION_SYSTEM_PROMPT",
    "ITERATIVE_OPTIMIZATION_USER_PROMPT",
    "CITATION_VERIFICATION_SYSTEM_PROMPT",
    "CITATION_VERIFICATION_USER_PROMPT",
    "WORKFLOW_SUMMARY_PROMPT",
]
